  
routes:
  /signup/: members\signup
  /signin/: members\signin
  /account/: members\account

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

#  /shiping/: 
#     template: shiping
#     data: page.shiping
#   /about/team/:
#     template: team
#     data: page.team